Jaycho 46/issue397
chromatic-protocol/frontend pull request #408
Opened 2023-08-01 18:51 UTC by jaycho-46

Fixes #397

2023-08-02 01:08 UTC, austin-builds approved these changes

2023-08-02 01:08 UTC, austin-builds commented on src/hooks/useTradeInput.ts
> +
All commits confirmed, and here is a suggestion.

```tsx
const { collateral, quantity } = method === 'collateral'
    ? { quantity: amount * leverage, collateral: amount }
    : { quantity: amount, collateral: amount * lossCutRate };
```

2023-08-04 04:19 UTC, not-thing approved these changes

2023-08-04 04:21 UTC, austin-builds reviewed
Max Fee Allowance seems to be increased only.

2023-08-04 05:20 UTC, kayden-fi commented on src/utils/number.ts
> +})();
IIFE seems to be unnecessary.

2023-08-04 05:41 UTC, kayden-fi commented on src/utils/number.ts
> +})();
And, this code is something wrong

2023-08-04 06:16 UTC, kayden-fi requested changes

2023-08-04 06:16 UTC, kayden-fi commented on src/hooks/useTradeInput.ts
> +}).format;
Need to add option value `roundingMode: 'floor'`

2023-08-04 06:22 UTC, kayden-fi approved these changes

2023-08-04 06:27 UTC, merged