Dia/update darkmode
chromatic-protocol/frontend pull request #454
Opened 2023-08-09 09:29 UTC by dia-nn

- change darkmode setting
- add darkmode toggle
- darkmode detail
  - shadow
  - footer
  - todo: buttons, etc

2023-08-11 09:55 UTC, austin-builds reviewed
Can store if user use dark mode

2023-08-11 10:29 UTC, austin-builds reviewed
Show error border after user input

@dia-nn @jaycho-46

2023-08-11 13:13 UTC, jaycho-46 requested changes
@austin-builds 
'setIsInternalChange' is a mechanism to prevent the effect bubbling of data changes from external sources. 
This commit(https://github.com/chromatic-protocol/frontend/pull/454/commits/0ea54ad634a4db30c6185689b82cd5e89816fffd) will breaks the functionality.

2023-08-14 01:13 UTC, austin-builds commented
@jaycho-46 @dia-nn Commits reverted, now styling changed only.

2023-08-14 02:32 UTC, jaycho-46 approved these changes

2023-08-14 02:33 UTC, merged